import { sql } from "@/lib/db";

export async function ensureOrdersTable() {
  await sql`
    CREATE TABLE IF NOT EXISTS public.orders (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      ref_no TEXT UNIQUE NOT NULL,
      buyer TEXT,
      brand TEXT,
      style_id TEXT,
      style_name TEXT,
      order_qty NUMERIC(12,2) NOT NULL DEFAULT 0,
      delivery_date TIMESTAMPTZ,
      pfh_status TEXT NOT NULL DEFAULT 'PENDING',
      sop_status TEXT NOT NULL DEFAULT 'PENDING',
      ppm_status TEXT NOT NULL DEFAULT 'PENDING',
      approval_pending BOOLEAN NOT NULL DEFAULT false,
      vendor_last_active TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
}

export async function ensureOrderProcessTable() {
  await ensureOrdersTable();

  await sql`
    CREATE TABLE IF NOT EXISTS public.order_processes (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      order_id UUID UNIQUE NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
      vg_linked BOOLEAN NOT NULL DEFAULT false,
      ra_approved BOOLEAN NOT NULL DEFAULT false,
      fabric_pending INTEGER NOT NULL DEFAULT 0,
      fabric_pr INTEGER NOT NULL DEFAULT 0,
      fabric_po INTEGER NOT NULL DEFAULT 0,
      fabric_stock INTEGER NOT NULL DEFAULT 0,
      fabric_total INTEGER NOT NULL DEFAULT 0,
      trim_pending INTEGER NOT NULL DEFAULT 0,
      trim_pr INTEGER NOT NULL DEFAULT 0,
      trim_po INTEGER NOT NULL DEFAULT 0,
      trim_stock INTEGER NOT NULL DEFAULT 0,
      trim_total INTEGER NOT NULL DEFAULT 0,
      bulk_process INTEGER,
      fob INTEGER,
      bulk_emb INTEGER,
      rd_graded_pattern BOOLEAN NOT NULL DEFAULT false,
      pfh INTEGER,
      rd INTEGER,
      sop INTEGER,
      ppm INTEGER,
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;
}

export async function ensureSampleTrackingTables() {
  await ensureOrdersTable();

  await sql`
    CREATE TABLE IF NOT EXISTS public.sample_requests (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      our_ref TEXT UNIQUE NOT NULL,
      order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
      merchant TEXT,
      prepared_by TEXT,
      dept_from TEXT NOT NULL,
      item_type TEXT NOT NULL DEFAULT 'FABRIC',
      buyer TEXT,
      season TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS public.sample_stages (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      sample_request_id UUID NOT NULL REFERENCES public.sample_requests(id) ON DELETE CASCADE,
      stage TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'PENDING',
      started_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      assigned_to TEXT,
      remarks TEXT,
      updated_at TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(sample_request_id, stage)
    )
  `;
}

export async function ensureDesignVaultTable() {
  await ensureOrdersTable();

  await sql`
    CREATE TABLE IF NOT EXISTS public.design_vault_items (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      design_id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
      style_no TEXT NOT NULL,
      style_name TEXT,
      buyer TEXT NOT NULL,
      brand TEXT NOT NULL,
      designer TEXT NOT NULL,
      season TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'DESIGNING',
      image_url TEXT,
      additional_images TEXT[] NOT NULL DEFAULT '{}',
      order_id UUID,
      created_by TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;
}

export async function ensureDrEntriesTable() {
  await ensureOrdersTable();

  await sql`
    CREATE TABLE IF NOT EXISTS public.dr_entries (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      sr_no INTEGER NOT NULL DEFAULT 0,
      buyer TEXT,
      order_no TEXT NOT NULL,
      style_description TEXT,
      special_work TEXT,
      qty INTEGER NOT NULL DEFAULT 0,
      tod TIMESTAMPTZ,
      wk_number INTEGER,
      on_machine TEXT,
      off_machine TEXT,
      remarks TEXT,
      unit TEXT NOT NULL DEFAULT 'CTA',
      sheet_source TEXT,
      order_id UUID REFERENCES public.orders(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ DEFAULT NOW(),
      updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  const existing = await sql`SELECT COUNT(*)::int AS count FROM public.dr_entries`;
  if (Number(existing[0]?.count ?? 0) > 0) return;

  await sql`
    INSERT INTO public.dr_entries (
      sr_no,
      buyer,
      order_no,
      style_description,
      qty,
      tod,
      wk_number,
      unit,
      sheet_source,
      order_id
    )
    SELECT
      ROW_NUMBER() OVER (ORDER BY delivery_date ASC NULLS LAST, ref_no ASC)::int,
      buyer,
      ref_no,
      style_name,
      COALESCE(order_qty, 0)::int,
      delivery_date,
      EXTRACT(WEEK FROM delivery_date)::int,
      'CTA',
      'orders',
      id
    FROM public.orders
  `;
}

export async function ensureNotificationsTable() {
  await ensureOrdersTable();

  await sql`
    CREATE TABLE IF NOT EXISTS public.notifications (
      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      reff_no TEXT,
      style_name TEXT,
      message TEXT NOT NULL,
      created_by TEXT,
      is_read BOOLEAN NOT NULL DEFAULT false,
      type TEXT NOT NULL DEFAULT 'INFO',
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `;

  const existing = await sql`SELECT COUNT(*)::int AS count FROM public.notifications`;
  if (Number(existing[0]?.count ?? 0) > 0) return;

  await sql`
    INSERT INTO public.notifications (reff_no, style_name, message, created_by, type)
    SELECT
      ref_no,
      style_name,
      CONCAT('Order ', ref_no, ' needs dashboard review'),
      'System',
      CASE
        WHEN approval_pending THEN 'ACTION'
        WHEN delivery_date < NOW() THEN 'RISK'
        ELSE 'INFO'
      END
    FROM public.orders
    WHERE approval_pending = true OR delivery_date <= NOW() + INTERVAL '14 days'
    ORDER BY delivery_date ASC NULLS LAST
    LIMIT 25
  `;
}
